#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
TICKET="$REPO_ROOT/.scratch/cerebrite-mvp/issues/06-android-platform-smoke-test.md"
MAP="$REPO_ROOT/.scratch/cerebrite-mvp/map.md"
APP_DIR="$REPO_ROOT/.scratch/cerebrite-mvp/android-smoke-test/app"
CORPUS_DIR="${TMPDIR:-/tmp}/cerebrite-smoke-corpus"

banner "Cerebrite: Android platform smoke test"
say "This validates the three risks flagged (but not blocking) by the tech-stack"
say "decision: does a bare Tauri app build & run on a real device, does the"
say "SQLite FTS5 + backlinks index rebuild sub-second on-device, and does"
say "git2-rs cross-compile and work on-device. Throwaway app lives at:"
note "$APP_DIR"

# ── Stage 1: prerequisites ─────────────────────────────────────────────────
stage "Prerequisites"
say "Checking for the tools this smoke test needs. Install anything missing,"
say "then re-run this script — it's safe to re-run from the top."

if command -v rustc >/dev/null 2>&1 && command -v cargo >/dev/null 2>&1; then
  step "Rust found: $(rustc --version)"
else
  warn "Rust not found."
  open_url "https://rustup.rs"
  step "Install Rust via rustup, open a new shell, then re-run this wizard."
  exit 1
fi

if [[ -z "${ANDROID_HOME:-}${ANDROID_SDK_ROOT:-}" ]]; then
  warn "ANDROID_HOME / ANDROID_SDK_ROOT not set."
  open_url "https://developer.android.com/studio"
  step "Install Android Studio, then in Settings > Android SDK install:"
  step "  - an SDK Platform (API 24+), the NDK (side by side), and Platform-Tools."
  step "Export ANDROID_HOME and NDK_HOME (see Tauri's Android prerequisites doc):"
  open_url "https://v2.tauri.app/start/prerequisites/#android"
  step "Then open a new shell (so the env vars are picked up) and re-run this wizard."
  exit 1
else
  step "Android SDK found at ${ANDROID_HOME:-$ANDROID_SDK_ROOT}"
fi

if ! command -v adb >/dev/null 2>&1; then
  warn "adb not on PATH (it ships in the SDK's platform-tools). Add it to PATH and re-run."
  exit 1
fi

rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android >/dev/null 2>&1 || true
step "Android Rust targets installed (aarch64, armv7, x86_64)."

if ! command -v cargo-tauri >/dev/null 2>&1 && ! cargo tauri --version >/dev/null 2>&1; then
  step "Installing tauri-cli (this takes a minute)..."
  cargo install tauri-cli --version "^2" --locked
fi
step "tauri-cli ready: $(cargo tauri --version 2>/dev/null || echo installed)"

say "Now plug in the real low/mid-range physical device over USB, enable"
say "Developer Options + USB debugging on it, and authorize this machine when prompted."
pause "Plugged in and authorized? Press Enter to check adb..."
say "Devices adb sees:"
adb devices -l || true
if ! confirm "Does the list above show a REAL device (not just an emulator)?"; then
  warn "No physical device detected. Connect one and re-run this wizard."
  exit 1
fi
ask DEVICE_MODEL "Device model + Android version, for the results record:"

# ── Stage 2: scaffold the throwaway app ────────────────────────────────────
stage "Scaffold a minimal Tauri app"
if [[ -d "$APP_DIR" ]]; then
  step "Found existing scaffold at $APP_DIR, reusing it."
else
  say "Scaffolding a vanilla Tauri 2.x app (JS template, no framework) at:"
  note "$APP_DIR"
  mkdir -p "$(dirname "$APP_DIR")"
  npm create tauri-app@latest "$(basename "$APP_DIR")" -- \
    --directory "$(dirname "$APP_DIR")" --manager npm --template vanilla --yes
  ( cd "$APP_DIR" && npm install )
  ( cd "$APP_DIR" && cargo tauri android init )
fi

RS_MAIN="$APP_DIR/src-tauri/src/lib.rs"
if [[ -f "$RS_MAIN" ]] && ! grep -q "fn ping" "$RS_MAIN"; then
  step "Adding a ping/pong Rust command for the round-trip check..."
  python3 - "$RS_MAIN" <<'PYEOF' || note "edit $RS_MAIN by hand: add a #[tauri::command] fn ping() -> String and register it in invoke_handler"
import sys, re
path = sys.argv[1]
src = open(path).read()
if "fn ping" not in src:
    src = '#[tauri::command]\nfn ping() -> String { "pong".into() }\n\n' + src
    src = re.sub(r'\.invoke_handler\(tauri::generate_handler!\[', '.invoke_handler(tauri::generate_handler![ping, ', src, count=1)
    open(path, "w").write(src)
PYEOF
fi
note "Frontend: call invoke('ping') from src/main.js (or index.html's inline script)"
note "and render the result somewhere visible, so a launch proves the round-trip."
pause "Wire up the ping call in the frontend now, then press Enter to continue..."

# ── Stage 3: Check 1 — builds and runs on-device ───────────────────────────
stage "Check 1: build + run on-device"
say "Building and installing the debug APK on the connected device..."
( cd "$APP_DIR" && cargo tauri android build --debug --target aarch64-linux-android ) \
  || warn "build failed — see output above"
APK=$(find "$APP_DIR/src-tauri/gen/android" -name "*-debug.apk" 2>/dev/null | head -n1 || true)
if [[ -n "$APK" ]]; then
  adb install -r "$APK" && step "Installed $APK"
  say "Launch the app on the device now and confirm the ping/pong round-trip works."
else
  warn "No debug APK found; build likely failed."
fi
if confirm "CHECK 1 — did the app build, launch, and show the ping round-trip?"; then
  CHECK1_RESULT="PASS"
else
  CHECK1_RESULT="FAIL"
fi
ask CHECK1_NOTES "Any rough edges (cold-start time, WebView version, crashes)?"

# ── Stage 4: synthetic corpus ───────────────────────────────────────────────
stage "Generate the synthetic ~500-file corpus"
say "Generating ~500 synthetic markdown notes (frontmatter id, headings, [[wikilinks])..."
rm -rf "$CORPUS_DIR"
mkdir -p "$CORPUS_DIR"
for i in $(seq 1 500); do
  id=$(printf 'page-%04d' "$i")
  link_a=$(printf 'page-%04d' $(( (i * 7) % 500 + 1 )))
  link_b=$(printf 'page-%04d' $(( (i * 13) % 500 + 1 )))
  {
    printf -- '---\nid: %s\ntitle: "Note %d"\ntags: [smoke-test]\n---\n\n' "$id" "$i"
    printf '# Note %d\n\nSome intro text linking to [[%s]] and [[%s]].\n\n' "$i" "$link_a" "$link_b"
    printf '## Section A\n\nBody text for section A, note %d.\n\n' "$i"
    printf '## Section B\n\nMore body text, referencing [[%s]] again.\n' "$link_a"
  } > "$CORPUS_DIR/$id.md"
done
step "Wrote 500 markdown files to $CORPUS_DIR"
say "Pushing the corpus onto the device's app-external files dir..."
DEVICE_CORPUS="/sdcard/Android/data/$(cd "$APP_DIR" && grep -m1 identifier src-tauri/tauri.conf.json | sed -E 's/.*"identifier"\s*:\s*"([^"]+)".*/\1/' 2>/dev/null || echo com.smoketest.app)/files/corpus"
adb shell "mkdir -p '$DEVICE_CORPUS'" || true
adb push "$CORPUS_DIR"/. "$DEVICE_CORPUS" >/dev/null || warn "adb push failed — copy the corpus onto the device by hand for the next stage."
step "Corpus pushed to $DEVICE_CORPUS on-device (adjust the app's read path to match if needed)."

# ── Stage 5: Check 2 — cold rebuild time ───────────────────────────────────
stage "Check 2: cold index-rebuild time"
say "Add a Rust command (e.g. bench_index) to $RS_MAIN that:"
step "1. Walks $DEVICE_CORPUS, reading each file's frontmatter id + headings + [[wikilinks]]."
step "2. Builds an on-device SQLite FTS5 table (rusqlite, bundled feature) + a backlinks table."
step "3. Times the walk+build with std::time::Instant and returns the elapsed ms."
say "Wire a button in the frontend that calls invoke('bench_index') and displays the ms."
note "Use the rusqlite crate with the 'bundled' feature so SQLite cross-compiles for Android."
pause "Implemented, rebuilt, reinstalled the APK, and tapped the button on-device? Press Enter..."
ask REBUILD_MS "Cold rebuild time reported on-device (milliseconds):"
if (( REBUILD_MS < 1000 )); then
  CHECK2_RESULT="PASS"
else
  CHECK2_RESULT="FAIL"
fi
say "Standing constraint: sub-second on Windows, Linux, AND Android. Result: $CHECK2_RESULT"

# ── Stage 6: Check 3 — git2-rs cross-compiles and works on-device ─────────
stage "Check 3: git2-rs cross-compilation + on-device git op"
say "In $APP_DIR/src-tauri/Cargo.toml, add: git2 = \"0.19\""
step "Rebuild for android: cargo tauri android build --debug --target aarch64-linux-android"
say "Watch for linker errors from libgit2/libssh2/openssl during that build — Android"
say "cross-compiles of git2-rs are notorious for needing NDK toolchain env vars."
note "If it fails to link, check git2-rs's Android notes and set CC_<target>/AR_<target> as needed."
say "Add a git_smoke_test command that clones a small throwaway repo (e.g. a tiny local"
say "bare repo pushed to the device, or a small public repo if the device has network)"
say "into the app's data dir, and returns the resulting commit count or an error string."
pause "Implemented, rebuilt, reinstalled, and tapped the button on-device? Press Enter..."
if confirm "Did git2-rs cross-compile cleanly AND the clone/pull succeed on-device?"; then
  CHECK3_RESULT="PASS"
else
  CHECK3_RESULT="FAIL"
fi
ask CHECK3_NOTES "Any cross-compilation gotchas (linker flags, env vars, missing libs)?"

# ── Stage 7: record the results ────────────────────────────────────────────
stage "Record the results"
say "Writing the answer onto the ticket and updating the map's Decisions-so-far."

TODAY="$(date +%Y-%m-%d)"
{
  printf '\n## Answer\n\n'
  printf -- '- Date: %s\n' "$TODAY"
  printf -- '- Device: %s\n' "$DEVICE_MODEL"
  printf -- '- Check 1 (builds + runs on-device): %s — %s\n' "$CHECK1_RESULT" "$CHECK1_NOTES"
  printf -- '- Check 2 (cold rebuild, ~500-file corpus): %s — %sms\n' "$CHECK2_RESULT" "$REBUILD_MS"
  printf -- '- Check 3 (git2-rs cross-compile + on-device op): %s — %s\n' "$CHECK3_RESULT" "$CHECK3_NOTES"
  if [[ "$CHECK1_RESULT" == "FAIL" || "$CHECK2_RESULT" == "FAIL" || "$CHECK3_RESULT" == "FAIL" ]]; then
    printf -- '\nAt least one check failed — per this ticket'"'"'s question, revisit [01-tech-stack-and-core-architecture](01-tech-stack-and-core-architecture.md) before proceeding with Android implementation.\n'
  fi
} >> "$TICKET"
sed -i 's/^Status: claimed$/Status: resolved/' "$TICKET"
step "Appended results to $TICKET and marked it resolved."

OVERALL="all checks passed"
if [[ "$CHECK1_RESULT" == "FAIL" || "$CHECK2_RESULT" == "FAIL" || "$CHECK3_RESULT" == "FAIL" ]]; then
  OVERALL="at least one check failed — see ticket for detail"
fi
DECISIONS_LINE="- [Android platform smoke test](issues/06-android-platform-smoke-test.md): $OVERALL on $DEVICE_MODEL (build/run \`$CHECK1_RESULT\`, rebuild \`$CHECK2_RESULT\` at ${REBUILD_MS}ms, git2-rs \`$CHECK3_RESULT\`)."
if [[ -f "$MAP" ]]; then
  awk -v line="$DECISIONS_LINE" '
    { print }
    /^## Decisions so far/ && !done { print ""; print line; done=1 }
  ' "$MAP" > "$MAP.tmp" && mv "$MAP.tmp" "$MAP"
  step "Appended a line to the map's Decisions-so-far."
else
  warn "Could not find $MAP — add the Decisions-so-far line by hand:"
  note "$DECISIONS_LINE"
fi

note "Throwaway app + corpus are at $APP_DIR and $CORPUS_DIR — delete them once you're"
note "satisfied the results are captured (they're not meant to become the real app)."

finish
